### ISSUE TITLE
Docker-compose shows an error during build

### ISSUE THREAD

**Issue by DarkDeddok** [calcom/docker#108]
I follow the instructions and get errors. help me pls 

![image](https://user-images.githubusercontent.com/57879696/167581016-a5f734fc-80eb-4f4a-bff0-1dd3698252f7.png)
![image](https://user-images.githubusercontent.com/57879696/167581159-2f79ea32-b3ff-40be-9cd6-82b01f70090e.png)

**Comment by thedevale** [comment]
> [builder 7/7] RUN yarn build:                                                                                                             
#0 0.404 yarn run v1.22.17                                                                                                                   
#0 0.439 $ turbo run build --scope="@calcom/web" --include-dependencies                                                                      
#0 0.979  WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo                     
#0 0.980 • Packages in scope: @calcom/app-store, @calcom/config, @calcom/core, @calcom/dailyvideo, @calcom/ee, @calcom/embed-core, @calcom/lib, @calcom/office365video, @calcom/prisma, @calcom/stripe, @calcom/tsconfig, @calcom/types, @calcom/ui, @calcom/web, @calcom/zoomvideo
#0 0.980 • Running build in 15 packages
#0 0.981 @calcom/prisma:build: cache miss, executing ba82f668acbda864
#0 0.981 @calcom/embed-core:build: cache miss, executing 5c52624cb46ccac9
#0 1.128 @calcom/embed-core:build: warning package.json: No license field
#0 1.147 @calcom/prisma:build: $ yarn prisma migrate deploy && yarn seed-app-store
#0 1.148 @calcom/embed-core:build: $ NEXT_PUBLIC_EMBED_FINGER_PRINT=$(git rev-parse --short HEAD) yarn __build
#0 1.164 @calcom/embed-core:build: fatal: Not a git repository (or any of the parent directories): .git
#0 1.339 @calcom/embed-core:build: warning package.json: No license field
#0 1.341 @calcom/prisma:build: $ /calcom/node_modules/.bin/prisma migrate deploy
#0 1.357 @calcom/embed-core:build: $ yarn tailwind && vite build
#0 1.530 @calcom/embed-core:build: warning package.json: No license field
#0 1.550 @calcom/embed-core:build: $ yarn tailwindcss -i ./src/styles.css -o ./src/tailwind.generated.css
#0 1.712 @calcom/embed-core:build: warning package.json: No license field
#0 1.731 @calcom/embed-core:build: $ /calcom/node_modules/.bin/tailwindcss -i ./src/styles.css -o ./src/tailwind.generated.css
#0 1.743 @calcom/embed-core:build: /bin/sh: 1: /calcom/node_modules/.bin/tailwindcss: not found
#0 1.759 @calcom/embed-core:build: error Command failed with exit code 127.
#0 1.759 @calcom/embed-core:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 1.779 @calcom/embed-core:build: error Command failed with exit code 127.
#0 1.779 @calcom/embed-core:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 1.801 @calcom/embed-core:build: error Command failed with exit code 127.
#0 1.801 @calcom/embed-core:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 1.823 @calcom/embed-core:build: error Command failed with exit code 127.
#0 1.823 @calcom/embed-core:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 1.829 @calcom/embed-core:build: Error: command finished with error: command (packages/embeds/embed-core) yarn run build exited (127)
#0 1.842 command (packages/embeds/embed-core) yarn run build exited (127)
#0 1.842 
#0 1.842  Tasks:    0 successful, 1 total
#0 1.842 Cached:    0 cached, 1 total
#0 1.842   Time:    1.336s 
#0 1.842 
#0 1.872 error Command failed with exit code 127.
#0 1.873 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 127


Same error here

**Comment by DarkDeddok** [comment]
that is, the problem in Dockerfile?

**Comment by DarkDeddok** [comment]
maybe you will make changes so that there are no errors in the build

**Comment by scantreed** [comment]
I'm having the same issue here

**Comment by anthonyneto** [comment]
Was able to get it to progress by changing this line: https://github.com/calcom/docker/blob/main/Dockerfile#L62 to this: ```COPY --from=deps /calcom/packages ./packages```

**Comment by DarkDeddok** [comment]
this did not solve the problem

**Comment by DarkDeddok** [comment]
I replaced in https://github.com/calcom/docker/blob/main/Dockerfile#L64 to this: `RUN yarn run` and progress went to Step 61/66, but got an error 

![image](https://user-images.githubusercontent.com/57879696/167830990-90e4f84e-d111-462b-9889-101edd04e7b9.png)

**Comment by chasebolt** [comment]
> Was able to get it to progress by changing this line: https://github.com/calcom/docker/blob/main/Dockerfile#L62 to this: `COPY --from=deps /calcom/packages ./packages`
> 
> The symlink for tailwind binary points to `tailwind -> ../../packages/embeds/embed-core/node_modules/tailwindcss/lib/cli.js` But the way the dockerfile is setup it copies from the unbuilt location in the project repo, need to copy from the deps build stage in the dockerfile.
> 
> Or so I think, could be wrong.

this solved my issue thanks!

**Comment by scantreed** [comment]
@chasebolt did you encounter this error after adding the fix? 

```
@calcom/prisma:build: error: Environment variable not found: DATABASE_URL.
@calcom/prisma:build:   -->  schema.prisma:6
@calcom/prisma:build:    | 
@calcom/prisma:build:  5 |   provider = "postgresql"
@calcom/prisma:build:  6 |   url      = env("DATABASE_URL")
@calcom/prisma:build:    | 
@calcom/prisma:build: 
@calcom/prisma:build: Validation Error Count: 1
```

**Comment by chasebolt** [comment]
yes because i didn't have a postgres instance running. which is required during the build. separate problem from this original error in this issue though.

**Comment by krumware** [comment]
The Prisma database connection is currently required during the build (new change) due to a refactor of the .env files to work around AWS env file size restrictions. a number of configuration items are being moved into the database. The temporary solution here is to checkout a version of calcom prior to that change and allow time for the refactor, but that obviously won't include the newest features.

Will address this asap

**Comment by scantreed** [comment]
thanks @krumware

**Comment by anthonyneto** [comment]
Added the above PR to address the missing tailwind binary, still need to look into the changes mentioned by @krumware Thanks!

**Comment by DarkDeddok** [comment]
guys, this is not a solution to the problem. Why you did not make changes to the file? so far i see the following errors

![image](https://user-images.githubusercontent.com/57879696/168568071-8c578a4c-6e29-47b5-917d-832d19fa2e39.png)

![image](https://user-images.githubusercontent.com/57879696/168567798-129136a8-cb0e-4802-b397-0516e38c2264.png)
