### ISSUE TITLE
How does one disable signup?

### ISSUE THREAD

**Issue by Julian-Hackenberg** [calcom/docker#191]
I can't find any documentation about this anywhere. 
Any help would be appreciated.

**Comment by PeerRich** [comment]
signup can currently only be disable by code by removing /signup.tsx file. there is no .env or database setting yet.

**Comment by prononext** [comment]
@Julian-Hackenberg  Analyzing the signup.tsx file there is one unpublished environment variable which is, when activated, redirecting the signup request to a Cal.com enterprise marketing page. So like this the signup is somehow disabled. The same page is also coming when inviting users. 

This environment variable can be used to achive it: `NEXT_PUBLIC_DISABLE_SIGNUP=true`

@PeerRich  would be nice to just let the invite functionality work, because there is a invite code sent with the request which can be a exeption. And also if there is already a environment variable, why do not just remove the "Dont have a account" on the login page when it is set?

**Comment by krumware** [comment]
Does this belong in calcom/docker or is this a core cal.com thing?

**Comment by prononext** [comment]
your right it is a docker issue I suppose.
