### ISSUE TITLE
Chore: Update node to version 18

### ISSUE THREAD

**Issue by krumware** [calcom/docker#221]
Tracking against https://github.com/calcom/cal.com/pull/7310
@emrysal

**Comment by eleith** [comment]
yarn v3 is also needed to support `v2.7.0` which was released today

**Comment by krumware** [comment]
Thanks for the tip!

**Comment by emrysal** [comment]
Thanks @eleith - beat me to it!

**Comment by palmtown** [comment]
Hello there,

Please note that "yarn global add turbo" is no longer supported as shown in the Error 1 below.  I used "yarn add turbo" and "yarn turbo prune --scope=@calcom/web --docker" however, the build hangs at "@calcom/web:build: info  - Collecting page data..." and timeouts with the error as shown in Error 2 below.  

I tried setting staticPageGenerationTimeout in next.config.js to a higher value, however, it just hangs for that amount of time and finally timeout.  

Any suggestions?  Only seems to happen when I'm trying to build a docker image.  However, if I don't use docker, then the build works fine.  Note that I'm using yarn 3.4.1and node 19.

**Error 1**
Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead

** Error 2**
Error: Collecting page data for [object Object] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout

**Comment by palmtown** [comment]
Here is the full error:

@calcom/web:build: info - Collecting page data...
@calcom/web:build: warn - Restarted collecting page data for [object Object] because it
took more than 60 seconds
@calcom/web:build: warn - See more info here https://nextjs.org/docs/messages/staticpage-
generation-timeout
@calcom/web:build:
@calcom/web:build: > Build error occurred
@calcom/web:build: Error: Collecting page data for [object Object] is still timing out
after 2 attempts. See more info here https://nextjs.org/docs/messages/page-datacollection-
timeout
@calcom/web:build: at onRestart (/usr/app/node_modules/next/dist/build
/index.js:601:35)
@calcom/web:build: at Worker.isPageStatic (/usr/app/node_modules/next/dist
/lib/worker.js:48:40)
@calcom/web:build: at process.processTicksAndRejections (node:internal/process
/task_queues:95:5)
@calcom/web:build: at async Span.traceAsyncFn (/usr/app/node_modules/next/dist/trace
/trace.js:79:20)
@calcom/web:build: at async /usr/app/node_modules/next/dist/build/index.js:725:52
@calcom/web:build: at async Span.traceAsyncFn (/usr/app/node_modules/next/dist/trace
/trace.js:79:20)
@calcom/web:build: at async Promise.all (index 49)
@calcom/web:build: at async /usr/app/node_modules/next/dist/build/index.js:664:17
@calcom/web:build: at async Span.traceAsyncFn (/usr/app/node_modules/next/dist/trace
/trace.js:79:20)
@calcom/web:build: at async /usr/app/node_modules/next/dist/build/index.js:625:170
@calcom/web:build: ERROR: command finished with error: command (/usr/app/apps/web) yarn
run build exited (1)
command (/usr/app/apps/web) yarn run build exited (1)
Tasks: 5 successful, 6 total
Cached: 0 cached, 6 total
Time: 4m34.758s
ERROR run failed: command exited (1)
The command '/bin/sh -c yarn build' returned a non-zero code: 1

**Comment by emrysal** [comment]
@palmtown may be unrelated, but we don't support n19 - reason is that one of our libraries only supports even numbered node releases. We don't discourage --ignore-engines for development purposes though.

**Comment by palmtown** [comment]
@emrysal Thanks for update and additionally information.  I tried with n18 as well, it hangs at the same place.

**Comment by palmtown** [comment]
Hello there,

I was able to successfully build the docker image using yarn 3.4.1 and node 18.15.0.  I created a pull request at https://github.com/calcom/docker/pull/225.
