### ISSUE TITLE
Only accessible at port 3000

### ISSUE THREAD

**Issue by johnnylinsf** [calcom/docker#241]
Hi everyone! I wanted to get Cal.com self-hosted set up on a Ubuntu VPS with Docker installed. I managed to get everything installed, but I found that it was only accessible at port 3000 on a custom domain.

So yourdomain.com wouldn't work, but yourdomain.com:3000 would work.

Do you have any tips or ideas on how I can resolve this?

**Comment by krumware** [comment]
Standard practice would be to put a load balancer / reverse proxy in front of the service, so that it would listen on 80 and 443, then tunnel the traffic to 3000 internally. That way you can manage the certificates outside of the service as well. I'd recommend Traefik if you're self-hosted. You can use the standard offerings from your cloud provider, if doing things there.

**Comment by johnnylinsf** [comment]
Thanks! I managed to get everything working!

**Comment by krumware** [comment]
Awesome!

**Comment by daniyalhaider99** [comment]
Hi @johnnylinsf 
Can you please share the steps you followed to get this working
Your help would be appreciated. Thanks
