### ISSUE TITLE
Docker hub Calendso not working

### ISSUE THREAD

**Issue by dotesfera** [calcom/docker#30]
Calendso on docker hub is dead or not working? I can't even pull it from docker hub...

**Comment by emrysal** [comment]
Docker hub circumvents docker-compose I suppose, so maybe Portainer would no longer use that file at all?

**Comment by dotesfera** [comment]
Where can I see Portainer logs on a failed stack deployment?

Is there any possibility to add this to docker hub? Because I could use my Synology docker to easily install this...

**Comment by dotesfera** [comment]
Any news on this?

**Comment by krumware** [comment]
moving on to this now that the build is stable

**Comment by dotesfera** [comment]
> moving on to this now that the build is stable

Is there any estimation when this is solved?

**Comment by krumware** [comment]
@dotesfera this is now building and pushing to the public image

**Comment by ovizii** [comment]
I would prefer using an image from dockerhub rather than building my own according to the instructions here so I am wondering, is this the image which is being maintained and suggested to use? 
There are a couple of others which also seem up-to-date hence my question.

=> https://hub.docker.com/r/calendso/calendso 
(Btw. I noticed this one also needs to be git cloned and then built, right? So, no usage right off the bat?)

**Comment by PeerRich** [comment]
I haven't used docker in a while but https://hub.docker.com/r/calendso/calendso should be ready to go @krumware right?

**Comment by ovizii** [comment]
maybe the instructions just have not been updated? I checked https://hub.docker.com/r/calendso/calendso and it still says:

![image](https://user-images.githubusercontent.com/837902/148844990-7b70e776-05b7-4f49-9bc8-94d3e14cc7a7.png)

**Comment by krumware** [comment]
@ovizii there are limitations being talked about and tracked here: https://github.com/calendso/docker/issues/56

The issue is that Calendso bakes variables into a static build, which forces us to have some form of build process in addition to the container run. There is another thread in calendso/calendso which talks about it as well. Because of the static build, we are losing some runtime convenience in favor of render speed, even though there are tools provided in next.js for runtime variables. (not my decision)

I'm testing a workaround outlined in the thread linked above

**Comment by krumware** [comment]
For localhost usage and demo, the dockerhub option works out of the box. For production configurability at runtime, we're working through that

**Comment by ovizii** [comment]
@krumware thanks, I had read a couple of topics here and I don't mind building the image myself. It seems I misread a couple of replies in this thread which led me to believe this was already no longer necessary.  
I'll give it a go, perfectly happy to see how it all works.

**Comment by krumware** [comment]
I'm working on adding a quick conditional to the start script to run the dev server at runtime, which could give us configurability we're looking for. Testing now

**Comment by dotesfera** [comment]
Made it work finally using docker hub, thank you!
